### Computer-Vision-Project: Rock Paper Scissors

Import Trained Model to Local System


In [1]:
import cv2
from tensorflow.keras.models import load_model
import numpy as np
model = load_model('Computer_Vision_RPS.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-04-20 16:20:16.884086: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-04-20 16:20:16.887145: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-20 16:20:16.896810: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


2022-04-20 16:20:21.125947: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-04-20 16:20:21.153082: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2395285000 Hz


[[8.7640816e-01 2.6901157e-04 8.4791782e-06 1.2331440e-01]]
[[9.9385935e-01 1.2619131e-06 2.2756729e-05 6.1167241e-03]]
[[4.6467137e-02 1.3106346e-05 2.5875712e-05 9.5349395e-01]]
[[1.9185802e-03 5.0828894e-05 4.5631480e-04 9.9757427e-01]]
[[3.6436669e-04 4.9324598e-07 3.7771048e-07 9.9963474e-01]]
[[9.9985671e-01 9.4717398e-06 1.2658793e-04 7.1980680e-06]]
[[9.9999630e-01 1.9333208e-07 3.2498931e-06 2.2486539e-07]]
[[9.99999762e-01 4.52987408e-08 1.07135676e-07 4.71495234e-08]]
[[9.9999619e-01 3.1915781e-06 5.6629563e-07 7.9215702e-08]]
[[9.9999893e-01 3.6910581e-07 5.4882798e-07 6.8534085e-08]]
[[9.9999559e-01 4.1475705e-06 2.4120908e-07 7.4633091e-09]]
[[1.0000000e+00 1.6561076e-09 2.0929252e-09 1.9189809e-08]]
[[9.9999988e-01 3.2246536e-08 1.5763338e-10 7.5284689e-08]]
[[9.9933881e-01 2.8083923e-06 6.4518594e-04 1.3119488e-05]]
[[9.9994695e-01 1.1063489e-07 3.8257724e-05 1.4682499e-05]]
[[9.9992573e-01 2.6865163e-07 3.0230161e-05 4.3744130e-05]]
[[9.99676347e-01 2.18200729e-08 1.16

KeyboardInterrupt: 