In [2]:
import cv2
from tensorflow.keras.models import load_model
import numpy as np
model = load_model('RPS_Model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

def move_list(value):
    Rev_Class_Map = {
        0: 'Rock',
        1: 'Paper',
        2: 'Scissors',
        3: 'Nothing'
            }
    return Rev_Class_Map[value]

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    print(prediction)
    prediction = np.argmax(prediction[0])
    final_prediction = move_list(prediction)
    print(final_prediction)
    cv2.imshow('frame', frame)
    # Press q to close the window
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

[[9.9982375e-01 8.6372847e-07 3.2859009e-06 1.7208872e-04]]
Rock
[[9.9993300e-01 5.8258576e-07 3.3768899e-07 6.6092784e-05]]
Rock
[[9.9969530e-01 1.6434730e-07 1.7716421e-07 3.0445732e-04]]
Rock
[[9.9261779e-01 2.5709198e-04 8.1709040e-06 7.1170060e-03]]
Rock
[[9.9999893e-01 3.5998287e-08 6.9531865e-08 8.6809342e-07]]
Rock
[[9.9859279e-01 1.8441480e-07 1.0748241e-06 1.4059521e-03]]
Rock
[[8.7699300e-01 1.1143387e-05 8.9046029e-05 1.2290676e-01]]
Rock
[[9.4162494e-01 8.7991884e-06 1.5511900e-05 5.8350820e-02]]
Rock
[[9.8072088e-01 4.0859777e-06 3.6100573e-06 1.9271422e-02]]
Rock
[[9.7909355e-01 1.1696018e-06 4.5864857e-07 2.0904806e-02]]
Rock
[[9.2614311e-01 1.6360807e-05 1.2599747e-06 7.3839344e-02]]
Rock
[[8.91702771e-01 1.45763861e-05 4.22697576e-06 1.08278416e-01]]
Rock
[[9.7862935e-01 2.6691528e-06 8.0216671e-07 2.1367136e-02]]
Rock
[[9.7732043e-01 6.6342081e-06 2.3318507e-06 2.2670664e-02]]
Rock
[[7.09645331e-01 1.12122325e-05 3.44145087e-06 2.90340006e-01]]
Rock
[[9.7615141e-01 4